name: Hello
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number || 'manual' }}
  cancel-in-progress: true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI is running!"
